debian/thumbnails /usr/share/cinnamon/
etc/xdg/menus/cinnamon*
usr/share/cinnamon-session
usr/share/cinnamon/
usr/share/desktop-directories/cinnamon*
usr/share/glib-2.0/schemas/*cinnamon*
usr/share/icons/
usr/share/polkit-1/actions/org.cinnamon.schema-install.policy
usr/share/polkit-1/actions/org.cinnamon.schema-remove.policy
usr/share/polkit-1/actions/org.cinnamon.settings-users.policy
usr/share/xsessions/cinnamon*
