.TH CINNAMON-SCREENSAVER-LOCK-DIALOG 1 2013-03-03  Cinnamon "cinnamon manual"
.SH NAME
cinnamon-screensaver-lock-dialog \- message setting for cinnamona screensaver
.SH SYNOPSIS
.SY cinnamon-screensaver-lock-dialog
.SH DESCRIPTION
.LP
\fBcinnamon-screensaver-lock-dialog\fP runs Graphical interface to set an
away message when executing cinnamon-screensaver.
.SH NOTE
\fBcinnamon-screensaver-lock-dialog\fP will work only if
cinnamon-screensaver. Fortunately, this will be called by cinnamon desktop
only if cinnamon-screensaver is installed.
.SH "SEE ALSO"
.BR gnome-screensaver-command (1)
