.TH CINNAMON-LOOKING-GLASS 1 2013-03-03  Cinnamon "cinnamon manual"
.SH NAME
cinnamon-looking-glass \- Debugging interface for Cinnamon
.SH SYNOPSIS
.SY cinnamon-looking-glass
.SH DESCRIPTION
.LP
\fBcinnamon-looking-glass\fP runs the graphical debugger interface for
cinnamon.
.SH "SEE ALSO"
.BR cinnamon (1)

