.TH CINNAMON-SCREENSAVER-LOCK-DIALOG 1 2013-03-03  Cinnamon "cinnamon manual"
.SH NAME
cinnamon-screensaver-lock-dialog \- message setting for cinnamon screensaver
.SH SYNOPSIS
.SY cinnamon-screensaver-lock-dialog
.SH DESCRIPTION
.LP
\fBcinnamon-screensaver-lock-dialog\fP runs the graphical interface to set
an away message when executing cinnamon-screensaver.
.SH NOTE
\fBcinnamon-screensaver-lock-dialog\fP will work only if
\fBcinnamon-screensaver\fP is installed. Fortunately, cinnamon desktop will
also call the dialog only if the latter is effectively installed.
.SH "SEE ALSO"
.BR gnome-screensaver-command (1)
